# Generated by Django 2.2.1 on 2022-11-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='duration',
            new_name='call_duration',
        ),
    ]
