# Generated by Django 2.2.1 on 2022-11-30 05:01

from django.db import migrations, models
from dbview.helpers import CreateView


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20221129_1743'),
    ]

    operations = [
        CreateView(
            name='BillingManagement',
            fields=[
                ('user_id', models.IntegerField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=32)),
                ('call_count', models.IntegerField(db_column='call_count')),
                ('block_count', models.IntegerField(db_column='block_count')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
